version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"

  # Monitor each custom action folder individually, GH doesnt support wildcards here
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/build-node-python"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/build-push-helm-chart"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/build-push-image"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/check-actor"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/check-helm-chart-version"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/get-ecr-scan-result"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/get-product-parameters"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/lint-docker"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/lint-github-actions"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/publish-node"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/publish-python"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/release-product-changes"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/release-source-changes"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/retag-image"
    schedule:
      interval: "weekly"
    reviewers:
      - "dvviktordelev"
