name: release-product-changes
description: release product
author: datavisyn

inputs:
  known_repositories:
    description: "known repositories as json"
    required: true
  repository_version:
    description: "version of the repository for the package.json"
    required: true
  ga_version:
    description: "github action version to use"
    required: true
  prepare_release:
    description: "true, if this is called to prepare the release; false if it runs to prepare the develop"
    default: true
    required: true

runs:
  using: "composite"
  steps:
    - name: change release
      run: |
        # change version in package.json
        version=$(jq -r '.version' ./package.json)
        sed -i "s|\"version\": \"$version\"|\"version\": \"$REPOSITORY_VERSION\"|gI" ./package.json
        cat ./package.json
        # change visyn_product
        # change app version
        echo -e "$(jq --arg version "$REPOSITORY_VERSION" '.branch = $version' ./visyn_product.json)" > ./visyn_product.json
        # get repositories
        known_repositories=$KNOWN_REPOSITORIES
        repositories=$(echo $known_repositories | jq -r '.')
        version=develop
        # change additionals
        readarray -t components < <(jq  -rc '.components | keys[]' ./visyn_product.json)
        for component in "${components[@]}"; do
          echo "component: $component"
          readarray -t additionals < <(jq --arg var "${component}" -rc '.components | to_entries | .[] | select(.key==$var)| .value.additionals[]?' ./visyn_product.json)
          component_json=$(jq --arg var "${component}" -rc '.components | to_entries | .[] | select(.key==$var) | .value | del(.additionals)' ./visyn_product.json)
          additional_json="["
          for additional in "${additionals[@]}"; do
            name=$(echo "$additional" | jq  -rc '.name')
            repository=$(echo "$additional" | jq  -rc '.repo')
            branch=$(echo "$additional" | jq  -rc '.branch')
            echo "$name"
            if [[ $PREPARE_RELEASE == "true" ]]; then
              version="v$(echo $repositories | jq -r --arg var $name '.[$var] | .version')"
            fi
            additional_json+="{\"name\": \"$name\", \"repo\": \"$repository\", \"branch\": \"$version\"},"
          done
          additional_json=${additional_json::-1}
          additional_json+="]"
          echo "$additional_json"
          if [[ ${#additional_json} -ge 2 ]] ; then
            component_json=$(echo $component_json | jq --argjson additionals "$additional_json" '. + {additionals: $additionals}')
          fi
          echo "$component_json"
          cat ./visyn_product.json
          echo -e "$(jq --arg var "${COMPONENT}" --argjson json "$component_json" '.components | .[$var] = $json' ./visyn_product.json)" > ./visyn_product.json
          cat ./visyn_product.json
        done

        #change version of github action references
        if [[ $PREPARE_RELEASE == "true" ]]; then
          find ./.github/workflows/ -name '*.yml' -exec sed -i "s/@main/@$GA_VERSION/g" {} \;
        else
          find ./.github/workflows/ -name '*.yml' -exec sed -i "s/@$GA_VERSION/@main/g" {} \;
        fi
      env:
        PREPARE_RELEASE: ${{ inputs.prepare_release }}
        REPOSITORY_VERSION: ${{ inputs.repository_version }}
        KNOWN_REPOSITORIES: ${{ inputs.known_repositories }}
        GA_VERSION: ${{ inputs.ga_version }}
      shell: bash
