name: build-push-helm-chart
description: Build helm chart and push it to ChartMuseum
author: datavisyn

inputs:
  chart_repository_url:
    description: "Helm chart repository URL where to push the chart"
    required: true
  chart_repository_username:
    description: "Helm chart repository username"
    required: true
  chart_repository_password:
    description: "Helm chart repository password"
    required: true
  current_directory:
    description: "Current directory for building the helm chart"
    required: true
  chart_version:
    description: "The version is used as chart version and application version. Use semantic versioning."
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up helm
      uses: azure/setup-helm@v3
      with:
        version: "v3.12.2"
      id: install
    - name: Print helm version
      run: |
        helm version
      shell: bash
    - name: Set up helm chart repository
      run: |
        helm repo add datavisyn $CHART_REPOSITORY_URL --username $CHART_REPOSITORY_USERNAME --password $CHART_REPOSITORY_PASSWORD
        helm repo update
      env:
        CHART_REPOSITORY_URL: ${{ inputs.chart_repository_url }}
        CHART_REPOSITORY_USERNAME: ${{ inputs.chart_repository_username }}
        CHART_REPOSITORY_PASSWORD: ${{ inputs.chart_repository_password }}
      shell: bash
    - name: Inspect and lint helm chart
      run: |
        cd $CURRENT_DIRECTORY
        helm inspect chart .
        helm lint
      env:
        CURRENT_DIRECTORY: ${{ inputs.current_directory }}
      shell: bash
    - name: Build helm chart
      run: |
        cd $CURRENT_DIRECTORY
        helm dependency update
        helm package . --version $CHART_VERSION --app-version $CHART_VERSION --destination $CURRENT_DIRECTORY
      env:
        CURRENT_DIRECTORY: ${{ inputs.current_directory }}
        CHART_VERSION: ${{ inputs.chart_version }}
      shell: bash
    - name: Push helm chart
      run: |
        cd $CURRENT_DIRECTORY
        helm push *.tgz datavisyn
      env:
        CURRENT_DIRECTORY: ${{ inputs.current_directory }}
      shell: bash
    - name: Remove helm chart
      run: |
        cd $CURRENT_DIRECTORY
        rm *.tgz
      env:
        CURRENT_DIRECTORY: ${{ inputs.current_directory }}
      shell: bash

