name: create workspace for product

inputs:
  generator_version:
    description: "generator version to use"
    default: "v11.0.0"
    required: true
    type: string
  phovea_type:  
    description: "phovea type (api or web)"
    default: "api"
    required: true
    type: string
  github_token:  
    description: "github token to use for clonging"
    default: "XXX"
    required: true
    type: string
  app_name:  
    description: "name of the app for the product"
    default: "XXX"
    required: true
    type: string        
runs:
  using: "composite"
  steps:
    - name: Install generator
      run: |
        npm install -g yo@4.3.0
        if [[ $GENERATOR_VERSION == "develop" ]]
          npm install -g "https://github.com/phovea/generator-phovea.git#develop"
        else
          npm install -g generator-phovea@$GENERATOR_VERSION
        fi  
      env:
        GENERATOR_VERSION: ${{ inputs.generator_version }}  
      shell: bash     
    - name: create workspace
      run: |
        mkdir -p ./tmp/$PHOVEA_TYPE
        cd ./tmp/$PHOVEA_TYPE
        phovea_type=$PHOVEA_TYPE
        name=$(jq --arg var ${phovea_type} -rc '.[] | select(.type == $var) | .repo' ../../phovea_product.json)
        name=$(echo "$name" | sed -e 's|.*/||')
        echo $name
        repository=https://$GITHUB_TOKEN@github.com/$(jq --arg var ${phovea_type} -rc '.[] | select(.type == $var) | .repo' ../../phovea_product.json).git
        echo $repository
        branch=$(jq --arg var ${phovea_type} -rc '.[] | select(.type == $var) | .branch' ../../phovea_product.json)
        echo $branch
        git clone -b $branch --depth 1 $repository $name
        readarray -t my_array < <(jq --arg var ${phovea_type} -rc '.[] | select(.type == $var) | .additional[]' ../../phovea_product.json)
        for additional in "${my_array[@]}"; do
          echo "$additional"
          name=$(echo $additional | jq  -rc '.name')
          name=$(echo "$name" | sed -e 's|.*/||')
          echo $name
          repository=https://$GITHUB_TOKEN@github.com/$(echo $additional | jq  -rc '.repo').git
          echo "$repository"
          branch=$(echo $additional | jq  -rc '.branch')
          echo "$branch"
          git clone -b $branch --depth 1 $repository $name
        done
      env: 
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PHOVEA_TYPE: ${{ inputs.phovea_type }}
      shell: bash             
    - name: update workspace
      run: |
        cd ./tmp/$PHOVEA_TYPE
        rm ./../../.yo-rc.json
        yo phovea:workspace --defaultApp=$APP_NAME --noAdditionals=true  --addWorkspaceRepos=false
        cp -r ./../../templates/$PHOVEA_TYPE/* .
        ls -lah
        cat ./package.json
      env:  
        PHOVEA_TYPE: ${{ inputs.phovea_type }}
        APP_NAME: ${{ inputs.app_name }}
      shell: bash  

