name: Build python source

inputs:
  python_version:
    description: "python version to use"
    default: "3.10"
    required: true
    type: string
  github_ro_token:  
    description: "github read-only token"
    default: "admin"
    required: true
    type: string
runs:
  using: "composite"
  steps:      
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python_version }}
    - name: Show python and pip version
      run: |
        python --version
        pip --version
      shell: bash  
    - name: Git config
      if: ${{ inputs.github_ro_token != '' }}
      run: git config --global url."https://$GITHUB_TOKEN@github".insteadOf https://github
      shell: bash
      env: 
        GITHUB_TOKEN: ${{ inputs.github_ro_token }}           
    - name: Install python dependencies
      run: make develop
      shell: bash
    - name: Show installed pip packages
      run: pip list || true
      shell: bash
    - name: Linting
      run: make lint check-format
      shell: bash             
    # - name: Run tests
    #   run: make test
    #   shell: bash
    - name: Build wheel
      run: make build 
      shell: bash 
