name: build-python
description: Build python via make build
author: datavisyn

inputs:
  python_version:
    description: "python version to use"
    default: "3.10"
    required: true
  github_ro_token:
    description: "github read-only token"
    default: "admin"
    required: true
  run_lint:
    default: true
    required: false
  run_test:
    default: true
    required: false
  run_build:
    default: true
    required: false
  disable_cache:
    description: "Set to true to disable caching"
    default: false
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up python (with cache)
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'
    # needs wheel for make
    #- name: Set up python (without cache)
    #  if: inputs.disable_cache == 'true'
    #  uses: actions/setup-python@v3
    #  with:
    #    python-version: ${{ inputs.python_version }}
    #- name: install additional requirements
    #  run: |
    #    pip install setuptools wheel
    #  shell: bash
    - name: Show python and pip version
      run: |
        python --version
        pip --version
      shell: bash
    - name: Git config
      if: ${{ inputs.github_ro_token != '' }}
      run: git config --global url."https://$GITHUB_TOKEN@github".insteadOf https://github
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_ro_token }}
    - name: Install python dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        make develop
      shell: bash
    - name: Show installed pip packages
      run: pip list || true
      shell: bash
    - name: Linting
      if: inputs.run_lint == 'true'
      run: |
        make lint check-format
      shell: bash
    - name: Run tests
      if: inputs.run_test == 'true'
      run: |
        make test
      shell: bash
    - name: Build wheel
      if: inputs.run_build == 'true'
      run: |
        make build
      shell: bash
