name: build-node
description: Build node sources via yarn
author: datavisyn

inputs:
  node_version:
    description: "node version to use"
    default: "16.16"
    required: true
  github_ro_token:
    description: "github read-only token"
    default: "admin"
    required: true
  npm_registry:
    description: "npm registry"
    default: "https://registry.npmjs.org/"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up node version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: ${{ inputs.npm_registry }}
    - name: Show node and npm version
      run: |
        corepack enable
        node -v
        npm -v
      shell: bash
    - name: Git config
      if: ${{ inputs.github_ro_token != '' }}
      run: |
        git config --global url."https://$GITHUB_TOKEN@github.com/".insteadOf ssh://git@github.com/
        git config --add --global url."https://$GITHUB_TOKEN@github.com/".insteadOf git@github.com:
      env:
        GITHUB_TOKEN: ${{ inputs.github_ro_token }}
      shell: bash
    # Enable yarn download cache, @see https://github.com/actions/setup-node/issues/325
    - name: Restore yarn cache
      uses: actions/cache@v3
      with:
        # This path is the global yarn cache, because for some reason the local .yarn/cache is not used. Maybe we need to set the cacheFolder, enableGlobalCache, ... options differently? @see https://yarnpkg.com/configuration/yarnrc#cacheFolder
        path: ~/.yarn/berry/cache/
        key: yarn-download-cache-${{ hashFiles('package.json') }}
        restore-keys: |
          yarn-download-cache-
    - name: Install dependencies
      run: yarn install --no-immutable --inline-builds
      shell: bash
    - name: Show installed dependencies
      run: yarn info --name-only
      shell: bash
    - name: Build
      run: npm run dist
      shell: bash
