name: publish-python
description: publish python source via twine to pypi
author: datavisyn

inputs:
  pypi_registry:
    description: "registry where to publish python package"
    required: false
  pypi_username:
    description: "username for python registry"
    required: true
  pypi_password:
    description: "passwort for python registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish to pip registry
      run: |
        echo "publish"
        pip install twine
        echo -e "[pypi]" >> $HOME/.pypirc
        echo -e "repository = $PYPI_REPOSITORY" >> $HOME/.pypirc
        echo -e "username = $TWINE_USERNAME" >> $HOME/.pypirc
        echo -e "password = $TWINE_PASSWORD" >> $HOME/.pypirc
        twine upload dist_python/*
      shell: bash
      env:
        PYPI_REPOSITORY: ${{ inputs.pypi_registry || 'https://upload.pypi.org/legacy/' }}
        TWINE_USERNAME: ${{ inputs.pypi_username }}
        TWINE_PASSWORD: ${{ inputs.pypi_password }}
