name: lint-github-actions
description: lint github action files via actionlint
author: datavisyn

runs:
  using: "composite"
  steps:
    - name: Check workflow files
      run: |
        sudo apt-get install -y shellcheck
        echo "::add-matcher::$GITHUB_ACTION_PATH/actionlint-matcher.json"
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/v1.6.22/scripts/download-actionlint.bash)
        ./actionlint -color
      shell: bash


