name: build-node-python
description: Build node sources via yarn and python via make
author: datavisyn

inputs:
  github_ro_token:
    description: "github read-only token"
    default: "admin"
    required: true
  run_parallel:
    description: "enables parallel running of node and python tasks"
    default: true
    required: true
  # Node
  enable_node:
    description: "enables the node part of the action"
    default: true
    required: true
  node_version:
    description: "node version to use"
    default: "20.9"
    required: true
  npm_registry:
    description: "npm registry"
    default: "https://registry.npmjs.org/"
    required: true
  enable_node_cache:
    description: "enables the yarn cache download and upload"
    required: false
    default: true
  download_yarn_lock:
    description: "downloads the node-yarn-lock artifact (only available when build-node was called before)"
    required: false
    default: false
  upload_yarn_lock:
    description: "uploads the node-yarn-lock artifact"
    required: false
    default: false # false as it is broken right now when actions run in parallel: the artifact name must be unique (so we have to pass the branch or so)
  upload_bundle:
    description: "uploads the bundle artifact"
    required: false
    default: false # false as it is broken right now when actions run in parallel: the artifact name must be unique (so we have to pass the branch or so)
  run_node_lint:
    default: true
    required: false
  run_playwright_browser_install:
    default: false
    required: false
  run_node_test:
    default: true
    required: false
  run_node_build:
    default: true
    required: false
  run_node_bundle:
    default: false
    required: false
  chromatic_enable:
    description: "Enable Chromatic tests"
    required: false
    type: boolean
    default: false
  chromatic_project_token:
    description: "Chromatic project token"
    required: false
  # Python
  enable_python:
    description: "enables the python part of the action"
    default: true
    required: true
  python_version:
    description: "python version to use"
    default: "3.10"
    required: true
  enable_python_cache:
    description: "deprecated and disabled as uv is usually faster anyways"
    required: false
    default: false
  run_python_lint:
    default: true
    required: false
  run_python_test:
    default: true
    required: false
  run_python_build:
    default: true
    required: false
  auto_fix_lint:
    description: "automatically fix linting errors when possible and commit changes"
    default: false
    required: false

runs:
  using: "composite"
  steps:
    # Node
    - name: Set up node version
      uses: actions/setup-node@v4
      if: inputs.enable_node == 'true'
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: ${{ inputs.npm_registry }}
    - name: Show node and npm version
      if: inputs.enable_node == 'true'
      run: |
        corepack enable
        node -v
        npm -v
      shell: bash
    # Python
    - name: Set up python
      uses: actions/setup-python@v5
      if: inputs.enable_python == 'true'
      with:
        python-version: ${{ inputs.python_version }}
        # cache: ${{ inputs.enable_python_cache == 'true' && 'pip' || null }} Disable cache as uv is probably faster anyways: https://github.com/actions/setup-python/issues/822
    - name: Install additional python requirements
      if: inputs.enable_python == 'true'
      run: |
        python -m pip install --upgrade pip uv
        uv pip install setuptools wheel --system
        python --version
        pip --version
        uv --version
      shell: bash
    - name: Install pgvector
      if: inputs.enable_python == 'true'
      run: |
        sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
        sudo apt-get install postgresql-16-pgvector -y
      shell: bash
    # General
    - name: Git config
      if: inputs.github_ro_token != ''
      run: |
        if [ -f ~/.gitconfig ]; then
          rm ~/.gitconfig
          touch ~/.gitconfig
        fi
        git config --global --replace-all url."https://$GITHUB_TOKEN@github.com/".insteadOf ssh://git@github.com/
        git config --add --global url."https://$GITHUB_TOKEN@github".insteadOf https://github
        git config --add --global url."https://$GITHUB_TOKEN@github.com/".insteadOf git@github.com:
        cat ~/.gitconfig
      env:
        GITHUB_TOKEN: ${{ inputs.github_ro_token }}
      shell: bash
    - uses: actions/download-artifact@v4
      # TODO: Remove the variable whenever we can ensure that build-node was called before
      if: inputs.enable_node == 'true' && inputs.download_yarn_lock == 'true'
      with:
        name: node-yarn-lock
    # Enable yarn download cache, @see https://github.com/actions/cache/tree/main/save#always-save-cache and https://github.com/actions/setup-node/issues/325
    - name: Restore yarn cache
      uses: actions/cache/restore@v4
      if: inputs.enable_node == 'true' && inputs.enable_node_cache == 'true'
      with:
        # This path is the global yarn cache, because for some reason the local .yarn/cache is not used. Maybe we need to set the cacheFolder, enableGlobalCache, ... options differently? @see https://yarnpkg.com/configuration/yarnrc#cacheFolder
        path: ~/.yarn/berry/cache/
        key: yarn-download-cache-${{ hashFiles('package.json') }}
        restore-keys: |
          yarn-download-cache-
    # Parallel build
    - name: Build node and python in parallel
      id: build
      run: |
        # Run node and python in parallel

        # Function to setup git for committing fixes
        setup_git_for_fixes() {
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        }

        # Function to commit lint fixes
        commit_lint_fixes() {
          local changes_made="$1"
          if [ "$changes_made" = "true" ]; then
            if git diff --quiet && git diff --cached --quiet; then
              echo "No changes to commit after running fixes"
              return 0
            fi
            
            echo "Committing lint fixes..."
            git add .
            if git diff --cached --quiet; then
              echo "No staged changes to commit"
              return 0
            fi
            git commit -m "Auto-fix: Apply linting and formatting fixes" || true
            git push || true
            echo "✓ Lint fixes committed and pushed"
          fi
        }

        # Define the node sequence of commands
        node_job() {
          set -e
          for i in {1..3}; do
            echo "Attempt $i of 3: Installing dependencies..."
            yarn install --no-immutable --inline-builds && break || {
              echo "Attempt $i failed. Retrying in 5 seconds..."
              sleep 5
            }
          done

          # Handle node linting with auto-fix capability
          if [ "$RUN_NODE_LINT" = "true" ]; then
            echo "Running node lint..."
            if ! yarn run lint --quiet; then
              if [ "$AUTO_FIX_LINT" = "true" ]; then
                echo "Node lint failed. Attempting to auto-fix..."
                setup_git_for_fixes
                yarn run lint:fix || echo "Warning: yarn lint:fix command failed or not available"
                
                echo "Re-running node lint after fixes..."
                if yarn run lint --quiet; then
                  echo "✓ Node lint passed after auto-fix"
                  commit_lint_fixes "true"
                else
                  echo "✗ Node lint still failing after auto-fix"
                  exit 1
                fi
              else
                echo "✗ Node lint failed and auto-fix is disabled"
                exit 1
              fi
            else
              echo "✓ Node lint passed"
            fi
          fi

          # Run other node tasks
          parallel_jobs=()
          if [ "$RUN_NODE_TEST" = "true" ]; then
            parallel_jobs+=("yarn run test")
          fi
          if [ "$RUN_NODE_BUILD" = "true" ]; then
            parallel_jobs+=("yarn run build")
          fi
          if [ "$RUN_NODE_BUNDLE" = "true" ]; then
            parallel_jobs+=("yarn run bundle:prod || yarn run webpack:prod")
          fi
          if [ "$RUN_PLAYWRIGHT_BROWSER_INSTALL" = "true" ]; then
            parallel_jobs+=("yarn playwright install --with-deps chromium")
          fi

          if [ ${#parallel_jobs[@]} -gt 0 ]; then
            parallel --jobs $1 --lb --halt-on-error 2 --verbose ::: "${parallel_jobs[@]}"
          fi
        }

        # Define the python sequence of commands
        python_job() {
          set -e
          make develop

          # Handle python linting with auto-fix capability
          if [ "$RUN_PYTHON_LINT" = "true" ]; then
            echo "Running python lint..."
            if ! make lint check-format; then
              if [ "$AUTO_FIX_LINT" = "true" ]; then
                echo "Python lint failed. Attempting to auto-fix..."
                setup_git_for_fixes
                make format || echo "Warning: make format command failed or not available"
                
                echo "Re-running python lint after fixes..."
                if make lint check-format; then
                  echo "✓ Python lint passed after auto-fix"
                  commit_lint_fixes "true"
                else
                  echo "✗ Python lint still failing after auto-fix"
                  exit 1
                fi
              else
                echo "✗ Python lint failed and auto-fix is disabled"
                exit 1
              fi
            else
              echo "✓ Python lint passed"
            fi
          fi

          # Run other python tasks
          parallel_jobs=()
          if [ "$RUN_PYTHON_TEST" = "true" ]; then
            parallel_jobs+=("make test")
          fi
          if [ "$RUN_PYTHON_BUILD" = "true" ]; then
            parallel_jobs+=("make build")
          fi

          if [ ${#parallel_jobs[@]} -gt 0 ]; then
            parallel --jobs $1 --lb --halt-on-error 2 --verbose ::: "${parallel_jobs[@]}"
          fi
        }

        # Export the functions so they can be used by GNU parallel
        export -f node_job
        export -f python_job
        export -f setup_git_for_fixes
        export -f commit_lint_fixes

        # If RUN_PARALLEL is set, set --jobs to 0, otherwise to 1
        N_JOBS=1
        if [ "$RUN_PARALLEL" = "true" ]; then
          N_JOBS=0
        fi

        final_jobs=()
        if [ "$RUN_NODE" = "true" ]; then
          final_jobs+=("node_job $N_JOBS")
        fi
        if [ "$RUN_PYTHON" = "true" ]; then
          final_jobs+=("python_job $N_JOBS")
        fi

        parallel --jobs $N_JOBS --lb --halt-on-error 2 --verbose ::: "${final_jobs[@]}"
      shell: bash
      env:
        RUN_PARALLEL: ${{ inputs.run_parallel }}
        RUN_NODE: ${{ inputs.enable_node }}
        RUN_PYTHON: ${{ inputs.enable_python }}
        RUN_PLAYWRIGHT_BROWSER_INSTALL: ${{ inputs.run_playwright_browser_install }}
        RUN_NODE_LINT: ${{ inputs.run_node_lint }}
        RUN_NODE_TEST: ${{ inputs.run_node_test }}
        RUN_NODE_BUILD: ${{ inputs.run_node_build }}
        RUN_NODE_BUNDLE: ${{ inputs.run_node_bundle }}
        RUN_PYTHON_LINT: ${{ inputs.run_python_lint }}
        RUN_PYTHON_TEST: ${{ inputs.run_python_test }}
        RUN_PYTHON_BUILD: ${{ inputs.run_python_build }}
        AUTO_FIX_LINT: ${{ inputs.auto_fix_lint }}
    # Node
    - name: Save yarn cache
      uses: actions/cache/save@v4
      if: inputs.enable_node == 'true' && steps.build.outcome == 'success' && inputs.enable_node_cache == 'true'
      with:
        # This path is the global yarn cache, because for some reason the local .yarn/cache is not used. Maybe we need to set the cacheFolder, enableGlobalCache, ... options differently? @see https://yarnpkg.com/configuration/yarnrc#cacheFolder
        path: ~/.yarn/berry/cache/
        key: yarn-download-cache-${{ hashFiles('package.json') }}
    - uses: actions/upload-artifact@v4
      if: inputs.enable_node == 'true' && inputs.upload_yarn_lock == 'true'
      with:
        name: node-yarn-lock
        path: ./yarn.lock
    - uses: actions/upload-artifact@v4
      if: inputs.enable_node == 'true' && inputs.run_node_bundle == 'true' && inputs.upload_bundle == 'true'
      with:
        name: node-bundle
        path: ./bundles
    # Chromatic
    - name: Run Chromatic
      if: inputs.enable_node == 'true' && inputs.chromatic_enable == 'true'
      uses: chromaui/action@v12.0.0
      with:
        exitZeroOnChanges: true
        exitOnceUploaded: true
        projectToken: ${{ inputs.chromatic_project_token }}
