name: publish-node
description: publish node source via npm
author: datavisyn

inputs:
  npm_token:
    description: "npm token"
    default: "admin"
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish to npm
      run: |
        echo "publish"
        npm publish
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
