name: Build Frontend and Backend Images for Product

on: workflow_call

concurrency:
  group: '${{ github.workflow }}-${{ github.ref || github.head_ref }}'
  cancel-in-progress: true

env:
  GENERATOR_VERSION: "v11.0.0"
  TIME_ZONE: "Europe/Vienna"

permissions:
  id-token: write
  contents: read 

jobs:
  prepare-build:
    outputs:
      app: ${{ steps.get-parameters.outputs.app }}  
      api_repo: ${{ steps.get-parameters.outputs.api_repo }}  
      web_repo: ${{ steps.get-parameters.outputs.web_repo }}
      stage: ${{ steps.get-parameters.outputs.stage }}
      customer: ${{ steps.get-parameters.outputs.customer }}
      sub_app: ${{ steps.get-parameters.outputs.sub_app }}
      aws: ${{ steps.get-parameters.outputs.aws }}
      image_tag1: ${{ steps.get-parameters.outputs.image_tag1 }}
      image_tag2: ${{ steps.get-parameters.outputs.image_tag2 }}
    runs-on: ubuntu-20.04
    steps: 
      # checkout specific repository    
      - uses: actions/checkout@v3
      - name: get parameters
        id: get-parameters
        run: |
          product_name=${{ github.event.repository.name }}
          post_fix=_product
          product_name=${product_name%$post_fix}
          app=$(jq  -rc '.[] | select(.type == "web") | .name' ./phovea_product.json)
          api_repo="$product_name/"$(jq  -rc '.[] | select(.type == "api") | .label' ./phovea_product.json)
          web_repo="$product_name/"$(jq  -rc '.[] | select(.type == "web") | .label' ./phovea_product.json)
          # get everything from branch name
          # branchname should look <develop|master|main>_<sub_app>_<customer>_<aws>
          # for release candidates the branch name should look like: rc_<version>_<sub_app>_<customer>_<aws>
          branch_name=${{ github.ref }}
          branch_name=${branch_name##*/}
          echo $branch_name
          post_fix=_aws
          aws=false
          if [[ $branch_name == *"_aws"* ]]; then
            aws=true
            branch_name=${branch_name%$post_fix}
          fi
          # develop branch
          if [[ $branch_name == develop* ]] ; then 
            stage=develop
            branch_name=${branch_name#develop_}
            branch_name=${branch_name#develop}
          fi
          # master / main branch
          if [[ $branch_name == master* ]] || [[ $a == main* ]] ; then 
            stage=production
            branch_name=${branch_name#main_}
            branch_name=${branch_name#main}
            branch_name=${branch_name#master_}
            branch_name=${branch_name#master}
          fi
          # release candidate
          if [[ $branch_name == rc_* ]] ; then 
            stage=production
            branch_name=${branch_name#rc_}
            rc_candidate=rc_${branch_name%%_*}
            branch_name=${branch_name#*_}
          fi
          # version tag
          if [[ $branch_name == v* ]] ; then 
            stage=production
            branch_name=${branch_name#v}
            version=${branch_name%%_*}
            branch_name=${branch_name#*_}
          fi          
          # check customer
          customer=datavisyn
          dv_customers=${{ secrets.DV_CUSTOMERS }}
          array=($(echo "${dv_customers}" | tr ',' "\n"))
          for c in "${array[@]}"
          do
            if [[ ${{ github.ref }} =~ _${c}_ ]]; then
              branch_name=${branch_name//_$c/}
              customer=$c
            fi
          done
          # check if there is a sub_app part
          sub_app=$(echo $branch_name | sed s/_//)
          # get image tags
          image_tag1=''
          if [[ $stage == develop ]] ; then
            image_tag1+=develop_
          else
            if [[ ! -z $rc_candidate ]] ; then
              image_tag1+=${rc_candidate}_
            elif [[ ! -z $version ]] ; then
              image_tag1+=${version}_ 
            else
              image_tag1+=main_              
            fi  
          fi
          if [[ ! -z $sub_app ]] ; then
              image_tag1+=${sub_app}_
          fi
          if [[ $customer != "datavisyn" ]] ; then
              image_tag1+=${customer}_
          fi
          image_tag1=${image_tag1::-1}
          image_tag2=$image_tag1-$(TZ=${{ env.TIME_ZONE }} date +%Y%m%d-%H%M%S)
          aws=true
          # echo parameters
          echo "app=$app"
          echo "api_repo=$api_repo"
          echo "web_repo=$web_repo"
          echo "stage=$stage"
          echo "customer=$customer"
          echo "sub_app=$sub_app"
          echo "aws=$aws"
          echo "image_tag1=$image_tag1"
          echo "image_tag2=$image_tag2"
          # echo to output
          echo "::set-output name=app::$app"
          echo "::set-output name=api_repo::$api_repo"
          echo "::set-output name=web_repo::$web_repo"
          echo "::set-output name=stage::$stage"
          echo "::set-output name=customer::$customer"
          echo "::set-output name=sub_app::$sub_app"
          echo "::set-output name=aws::$aws"
          echo "::set-output name=image_tag1::$image_tag1"
          echo "::set-output name=image_tag2::$image_tag2"
  build-node:
    needs: prepare-build 
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.19"]
    steps: 
      # checkout specific product repository    
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}
      - name: Set up node version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ env.NPM_REGISTRY }}
      - name: Show node and npm version
        run: |
          node -v
          npm -v
      - name: Git config
        if: "${{ env.GITHUB_TOKEN != '' }}"
        run: |
          git config --global url.https://${{ env.GITHUB_TOKEN }}@github.com/.insteadOf ssh://git@github.com/
        env: 
          GITHUB_TOKEN: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}
      # checkout this workflow repository to get actions
      - uses: actions/checkout@v3
        with:
          repository: datavisyn/github-workflows
          ref: main
          path: ./tmp/github-workflows
      - uses: ./tmp/github-workflows/.github/actions/create-product-workspace
        with:
          phovea_type: web
          generator_version: ${{ env.GENERATOR_VERSION }}
          github_token:  ${{ secrets.DATAVISYN_BOT_REPO_TOKEN ||  github.token }}
          app_name:  ${{ needs.prepare-build.outputs.app }}             
      - name: install dependencies
        run: |
          cd ./tmp/web
          npm i     
      - name: show installed dependencies
        run: |
          cd ./tmp/web
          npm list --depth=1 || true
      - name: Build
        run: |
          cd ./tmp/web
          npm run dist
      - uses: ./tmp/github-workflows/.github/actions/build-push-image
        if: ${{ needs.prepare-build.outputs.aws && needs.prepare-build.outputs.aws == 'true' }}
        with:
          aws_role: ${{ secrets.AWS_ECR_ROLE }} 
          ecr_registry: ${{ secrets.AWS_ECR_REGISTRY }}
          ecr_repository: ${{ needs.prepare-build.outputs.web_repo }}
          docker_file: ./deploy/web/Dockerfile
          CURRENT_DIRECTORY: ./tmp/web
          image_tag1: ${{ needs.prepare-build.outputs.image_tag1 }}
          image_tag2: ${{ needs.prepare-build.outputs.image_tag2 }}          

  build-python:
    needs: prepare-build 
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps: 
      # checkout specific product repository    
      - uses: actions/checkout@v3
      # need node because of the generator
      - name: Set up node version 
        uses: actions/setup-node@v3
        with:
          node-version: "14.19"
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Show python and pip version
        run: |
          python --version
          pip --version
      - name: Git config
        if: "${{ env.GITHUB_TOKEN != '' }}"
        run: |
          git config --global url.https://${{ env.GITHUB_TOKEN }}@github.com/.insteadOf ssh://git@github.com/
        env: 
          GITHUB_TOKEN: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}       
      # needs wheel for make
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      # checkout this workflow repository to get actions
      - uses: actions/checkout@v3
        with:
          repository: datavisyn/github-workflows
          ref: main
          path: ./tmp/github-workflows
      - uses: ./tmp/github-workflows/.github/actions/create-product-workspace
        with:
          phovea_type: api
          generator_version: ${{ env.GENERATOR_VERSION }}
          github_token:  ${{ secrets.DATAVISYN_BOT_REPO_TOKEN ||  github.token }}
          app_name:  ${{ needs.prepare-build.outputs.app }}   
      - name: Build
        run: |
          cd ./tmp/api
          mkdir -p ./build/source
          name=$(jq  -rc '.[] | select(.type == "api") | .repo' ../../phovea_product.json)
          name=$(echo "$name" | sed -e 's|.*/||')
          cd $name
          echo $name
          make build
          cp -r ./build/lib/* ../build/source/
          cp -r ./${name,,}.egg-info ../build/source/${name,,}.egg-info
          cd ..
          readarray -t my_array < <(jq  -rc '.[] | select(.type == "api") | .additional[]' ../../phovea_product.json)
          for additional in "${my_array[@]}"; do
            echo "$additional"
            name=$(echo $additional | jq  -rc '.name')
            name=$(echo "$name" | sed -e 's|.*/||')
            echo "$name"
            cd $name
            make build
            cp -r ./build/lib/* ../build/source/
            cp -r ./${name,,}.egg-info ../build/source/${name,,}.egg-info
            cd ..
          done
      - uses: ./tmp/github-workflows/.github/actions/build-push-image
        if: ${{ needs.prepare-build.outputs.aws && needs.prepare-build.outputs.aws == 'true' }}
        with:
          aws_role: ${{ secrets.AWS_ECR_ROLE }} 
          ecr_registry: ${{ secrets.AWS_ECR_REGISTRY }}
          ecr_repository: ${{ needs.prepare-build.outputs.api_repo }}
          docker_file: ./deploy/api/Dockerfile
          CURRENT_DIRECTORY: ./tmp/api
          image_tag1: ${{ needs.prepare-build.outputs.image_tag1 }}
          image_tag2: ${{ needs.prepare-build.outputs.image_tag2 }}
  deploy:
    needs: [prepare-build, build-node, build-python] 
    runs-on: ubuntu-20.04
    if: ${{ needs.prepare-build.outputs.stage == 'develop' && needs.prepare-build.outputs.aws && needs.prepare-build.outputs.aws == 'true' }}
    steps:           
      - name: Deploy
        run: echo "Deploy" 
