name: Build and Publish Python and Node Repositories

on:
  workflow_call:
    inputs:
      publish:
        description: "true, if the package should be published to npm; otherwise false"
        default: false
        required: true
        type: boolean

env: 
  NPM_REGISTRY: "https://registry.npmjs.org/"
  PYPI_REGISTRY: "https://pypi.org/pypi"
  PYPI_USERNAME: "datavisyn"

permissions:
  contents: read

jobs:
  build-node:
    permissions:
      id-token: write
      contents: read  
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.19"]
    steps:      
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}
      - name: Set up node version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ env.NPM_REGISTRY }}
      - name: Show node and npm version
        run: |
          node -v
          npm -v
      - name: Git config
        if: "${{ env.GITHUB_TOKEN != '' }}"
        run: git config --global url.https://${{ env.GITHUB_TOKEN }}@github.com/.insteadOf ssh://git@github.com/
        env: 
          GITHUB_TOKEN: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}       
      - name: Install npm dependencies
        run:  npm install
      - name: Show installed npm dependencies
        run: npm list --depth=1 || true
      - name: Build
        run: npm run dist
      - name: Publish to npm
        if: ${{ inputs.publish && inputs.publish != 'false' }}
        run: echo "publish"
        #run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-python:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:      
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: datavisyn/github-workflows
          ref: main
          path: ./tmp/github-workflows
      - name: copy actions folder
        run: |
          mkdir -p ./.github/actions
          cp -r ./tmp/github-workflows/.github/actions/* ./.github/actions
      - uses: ./.github/actions/build-python
        with:
          python_version: ${{ matrix.python-version }}
          publish: ${{ inputs.publish}}
          pypi_registry: ${{ env.PYPI_REGISTRY }}
          pypi_username: ${{ env.PYPI_USERNAME }}
          pypi_password: ${{ secrets.PYPI_PASSWORD }} 
          github_ro_token:  ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }} 

