name: build-node

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: ${{ github.ref || github.head_ref }}
      chromatic_enable:
        description: 'Enable Chromatic Tests'
        required: false
        type: boolean
        default: false
      node_run_webpack:
        description: "Flag to always run the webpack production build."
        type: boolean
        required: false
        default: false
      runs_on:
        type: string
        required: false
        default: "ubuntu-22.04"
    secrets:
      DATAVISYN_BOT_REPO_TOKEN:
        required: false
      NODE_VERSION:
        required: false

env:
  NPM_REGISTRY: "https://registry.npmjs.org/"
  NODE_VERSION: "20.9"
  WORKFLOW_BRANCH: "main"

permissions:
  contents: read
  id-token: write

concurrency:
  group: '${{ github.workflow }}-${{ github.ref || github.head_ref }}'
  cancel-in-progress: true

jobs:
  build-node:
    concurrency:
      group: "node-${{ github.workflow }}-${{ github.ref || github.head_ref }}-${{ inputs.branch }}"
      cancel-in-progress: true
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          token: ${{ github.event.repository.private == true && secrets.DATAVISYN_BOT_REPO_TOKEN  || github.token  }}
          fetch-depth: ${{ inputs.chromatic_enable && '0' || '1' }}
      - name: Checkout github-workflows
        uses: actions/checkout@v4
        with:
          repository: datavisyn/github-workflows
          ref: ${{ env.WORKFLOW_BRANCH }}
          path: ./tmp/github-workflows
      - name: Build node
        uses: ./tmp/github-workflows/.github/actions/build-node
        with:
          node_version: ${{ secrets.NODE_VERSION || env.NODE_VERSION }}
          npm_registry: ${{ env.NPM_REGISTRY }}
          github_ro_token: ${{ github.event.repository.private == true && secrets.DATAVISYN_BOT_REPO_TOKEN || github.token  }}
          run_webpack: ${{ inputs.node_run_webpack }}
          enable_cache: ${{ inputs.runs_on != 'self-hosted' }}
      - name: Run Chromatic
        if: ${{ inputs.chromatic_enable }}
        uses: chromaui/action@v11.3.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
