name: Build and Publish Node

on:
  workflow_call:
    inputs:
      publish:
        description: 'true if the package should be published to npm; otherwise false'
        default: false
        required: true
        type: boolean
      npm_registry:
        description: 'npm registry to publish to'
        default: 'https://registry.npmjs.org/'
        type: string
    secrets:
      npm_token:
        description: "token for npm registry"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.19"]
    steps:      
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Show Node.js and npm version
        run: |
          node -v
          npm -v
      - name: Install npm dependencies
        run: |
          npm install
      - name: Show installed npm dependencies
        run: |
          npm list --depth=1 || true
      - name: Build
        run: |
          npm run dist
  publish-npm:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ inputs.npm_registry }}"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: ${{ inputs.npm_registry }}
      - run: npm ci
      - run: echo "publish"
  
      #- run: npm publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.npm_token}}  

