name: build-python

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: ${{ github.ref || github.head_ref }}
      trivy_enable:
        description: "Enable trivy scans on lock files"
        default: false  # Enable this by default?
        type: boolean
        required: false
      trivy_severity:
        description: "Severity for the trivy scans"
        type: string
        required: false
      runs_on:
        type: string
        required: false
        default: "ubuntu-22.04"
      python_version:
        type: string
        required: false

    secrets:
      DATAVISYN_BOT_REPO_TOKEN:
        required: false

env:
  WORKFLOW_BRANCH: "main"

permissions:
  contents: read
  id-token: write

concurrency:
  group: '${{ github.workflow }}-${{ github.ref || github.head_ref }}'
  cancel-in-progress: true

jobs:
  build-python:
    concurrency:
      group: "python-${{ github.workflow }}-${{ github.ref || github.head_ref }}-${{ inputs.branch }}"
      cancel-in-progress: true
    permissions:
      id-token: write
      contents: write
    runs-on: ${{ vars.BUILD_RUNS_ON_OVERRIDE || vars.RUNS_ON_OVERRIDE || inputs.runs_on || 'ubuntu-22.04' }}
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}
          token: ${{ github.event.repository.private == true && secrets.DATAVISYN_BOT_REPO_TOKEN  || github.token  }}
      - name: Checkout github-workflows
        uses: actions/checkout@v5
        with:
          repository: datavisyn/github-workflows
          ref: ${{ env.WORKFLOW_BRANCH }}
          path: ./tmp/github-workflows
      - name: Build python
        uses: ./tmp/github-workflows/.github/actions/build-node-python
        with:
          enable_node: false
          enable_python: true
          trivy_enable: ${{ inputs.trivy_enable }}
          trivy_severity: ${{ inputs.trivy_severity }}
          github_ro_token: ${{ github.event.repository.private == true && secrets.DATAVISYN_BOT_REPO_TOKEN || github.token  }}
          python_version: ${{ vars.PYTHON_VERSION || inputs.python_version }}
          enable_python_cache: ${{ inputs.runs_on != 'self-hosted' }}
