name: Build python and node repositories

on: workflow_call

env: 
  NPM_REGISTRY: "https://registry.npmjs.org/"
  PYPI_REGISTRY: "https://pypi.org/pypi"
  PYPI_USERNAME: "datavisyn"

permissions:
  contents: read

jobs:
  build-node:
    permissions:
      id-token: write
      contents: read  
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.19"]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }} # has to set because otherwise it will not work
      - uses: actions/checkout@v3
        with:
          repository: datavisyn/github-workflows
          ref: main
          path: ./tmp/github-workflows
      - uses: ./tmp/github-workflows/.github/actions/build-node
        with:
          node_version: ${{ matrix.node-version }}
          npm_registry: ${{ env.NPM_REGISTRY }}
          github_ro_token:  ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}           

  build-python:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:      
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: datavisyn/github-workflows
          ref: main
          path: ./tmp/github-workflows
      - uses: ./tmp/github-workflows/.github/actions/build-python
        with:
          python_version: ${{ matrix.python-version }}
          github_ro_token:  ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }} 

