name: Build and Publish Node Repositories

on:
  workflow_call:
    inputs:
      publish:
        description: "true, if the package should be published to npm; otherwise false"
        default: false
        required: true
        type: boolean
env: 
  NPM_REGISTRY: "https://registry.npmjs.org/"


jobs:
  build-node:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.19"]
    steps:      
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ env.NPM_REGISTRY }}
      - name: Show Node.js and npm version
        run: |
          node -v
          npm -v
      - name: Install npm dependencies
        run: npm install
        env: 
          NODE_AUTH_TOKEN: ${{secrets.DATAVISYN_GITHUB_TOKEN}}        
      - name: Show installed npm dependencies
        run: npm list --depth=1 || true
      - name: Build
        run: npm run dist
      - name: publish to npm
        if: ${{ inputs.publish && inputs.publish != 'false' }}
        run: echo "publish"
        #run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.DATAVISYN_GITHUB_TOKEN}}
