name: Build and Publish Python and Node Repositories

on:
  workflow_call:
    inputs:
      publish:
        description: "true, if the package should be published to npm; otherwise false"
        default: false
        required: true
        type: boolean

env: 
  NPM_REGISTRY: "https://registry.npmjs.org/"
  PYPI_REGISTRY: "https://pypi.org/pypi"
  PYPI_USERNAME: "datavisyn"


jobs:
  build-node:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.19"]
    steps:      
      - uses: actions/checkout@v3
      - name: Set up node version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ env.NPM_REGISTRY }}
      - name: Show node and npm version
        run: |
          node -v
          npm -v
      - name: Git config
        if: "${{ env.GITHUB_TOKEN != '' }}"
        run: git config --global url.https://${{ env.GITHUB_TOKEN }}@github.com/.insteadOf ssh://git@github.com/
        env: 
          GITHUB_TOKEN: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}       
      - name: Install npm dependencies
        run:  npm install
      - name: Show installed npm dependencies
        run: npm list --depth=1 || true
      - name: Build
        run: npm run dist
      - name: Publish to npm
        if: ${{ inputs.publish && inputs.publish != 'false' }}
        run: echo "publish"
        #run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  build-python:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:      
      - uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Show python and pip version
        run: |
          python --version
          pip --version
      - name: Git config
        if: "${{ env.GITHUB_TOKEN != '' }}"
        run: git config --global url."https://${{ env.GITHUB_TOKEN }}@github".insteadOf https://github
        env: 
          GITHUB_TOKEN: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}           
      - name: Install python dependencies
        run: make develop
      - name: Show installed pip packages
        run: pip list || true
      - name: Linting
        run: make lint check-format                  
      - name: Run tests
        run: make test
      - name: Publish to pip registry
        if: ${{ inputs.publish && inputs.publish != 'false' }}
        run: |
           echo "publish"
           pip install twine
#          echo -e "[pypi]" >> ~/.pypirc
#          echo -e "repository = $PYPI_REPOSITORY" >> ~/.pypirc
#          echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
#          echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
#          twine upload dist_python/*
        env: 
          PYPI_REPOSITORY: ${{env.PYPI_REGISTRY}}
          PYPI_USERNAME: ${{env.PYPI_USERNAME}}
          PYPI_PASSWORD: ${{secrets.PYPI_PASSWORD}} 
