name: build-node

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: ${{ github.ref || github.head_ref }}
      chromatic_enable:
        description: 'Enable Chromatic tests'
        required: false
        type: boolean
        default: false
      node_run_webpack:
        description: "Flag to always run the webpack production build."
        type: boolean
        required: false
        default: false
      runs_on:
        type: string
        required: false
        default: "ubuntu-22.04"
      node_version:
        type: string
        required: false

    secrets:
      DATAVISYN_BOT_REPO_TOKEN:
        required: false
      CHROMATIC_PROJECT_TOKEN:
        required: false

env:
  WORKFLOW_BRANCH: "main"

permissions:
  contents: read
  id-token: write

concurrency:
  group: '${{ github.workflow }}-${{ github.ref || github.head_ref }}'
  cancel-in-progress: true

jobs:
  build-node:
    concurrency:
      group: "node-${{ github.workflow }}-${{ github.ref || github.head_ref }}-${{ inputs.branch }}"
      cancel-in-progress: true
    permissions:
      id-token: write
      contents: write
    runs-on: ${{ vars.BUILD_RUNS_ON_OVERRIDE || vars.RUNS_ON_OVERRIDE || inputs.runs_on || 'ubuntu-22.04' }}
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}
          token: ${{ github.event.repository.private == true && secrets.DATAVISYN_BOT_REPO_TOKEN  || github.token  }}
          fetch-depth: ${{ inputs.chromatic_enable && '0' || '1' }}
      - name: Checkout github-workflows
        uses: actions/checkout@v5
        with:
          repository: datavisyn/github-workflows
          ref: ${{ env.WORKFLOW_BRANCH }}
          path: ./tmp/github-workflows
      - name: Build node
        uses: ./tmp/github-workflows/.github/actions/build-node-python
        with:
          enable_node: true
          enable_python: false
          node_version: ${{ vars.NODE_VERSION || inputs.node_version }}
          npm_registry: ${{ vars.NPM_REGISTRY }}
          github_ro_token: ${{ github.event.repository.private == true && secrets.DATAVISYN_BOT_REPO_TOKEN || github.token  }}
          run_node_bundle: ${{ inputs.node_run_webpack }}
          chromatic_enable: ${{ inputs.chromatic_enable }}
          chromatic_project_token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
