name: Build python repositories

on: 
  workflow_call:
    secrets:
      DATAVISYN_BOT_REPO_TOKEN:
        required: false

env: 
  PYPI_REGISTRY: "https://upload.pypi.org/legacy/"
  PYPI_USERNAME: "test"

permissions:
  contents: read
  id-token: write  

concurrency:
  group: '${{ github.workflow }}-${{ github.ref || github.head_ref }}'
  cancel-in-progress: true  

jobs:
  build-python:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      # checkout specific source repository  
      - uses: actions/checkout@v3
      # checkout this workflow repository to get actions
      - uses: actions/checkout@v3
        with:
          repository: datavisyn/github-workflows
          ref: ${{ github.ref }}
          path: ./tmp/github-workflows
      - uses: ./tmp/github-workflows/.github/actions/build-python
        with:
          python_version: ${{ matrix.python-version }}
          github_ro_token: ${{ github.event.repository.private == true && secrets.DATAVISYN_BOT_REPO_TOKEN || github.token }}
