name: Build and Publish Python

on:
  workflow_call:
    inputs:
      publish:
        description: "true, if the package should be published to npm; otherwise false"
        default: false
        required: true
        type: boolean
      pypi_repository:
        description: "pypi registry to publish to"
        default: "https://pypi.org/pypi"
        type: string
      pypi_username:
        description: "pypi username"
        default: "testUser"
        type: string
    secrets:
      pypi_password:
        description: "password of pypi registry"
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:      
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Show python and pip version
        run: |
          python --version
          pip --version
      - name: Install python dependencies
        run: |
          make develop
      - name: Show installed pip packages
        run: |
          pip list || true
      - name: Linting
        run: |
          make lint check-format                  
      - name: Run tests
        run: |
          make test
      - name: publish to pip registry
        if: ${{ inputs.publish && inputs.publish != 'false' }}
        run: |
           echo "publish"
           pip install twine
#          echo -e "[pypi]" >> ~/.pypirc
#          echo -e "repository = $PYPI_REPOSITORY" >> ~/.pypirc
#          echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
#          echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
#          twine upload dist_python/*
        env: 
          PYPI_REPOSITORY: ${{secrets.pypi_repository}}
          PYPI_USERNAME: ${{secrets.pypi_username}}
          PYPI_PASSWORD: ${{secrets.pypi_password}}        
