name: Build and Publish Python Repositories

on:
  workflow_call:
    inputs:
      publish:
        description: "true, if the package should be published to npm; otherwise false"
        default: false
        required: true
        type: boolean

env: 
  NPM_REGISTRY: "https://registry.npmjs.org/"
  PYPI_REGISTRY: "https://pypi.org/pypi"
  PYPI_USERNAME: "test"

jobs:
  build-python:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:      
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Show python and pip version
        run: |
          python --version
          pip --version
      - name: Install python dependencies
        run: |
          git config --global url."https://${{ secrets.DATAVISYN_GITHUB_TOKEN }}@github".insteadOf https://github
          make develop
      - name: Show installed pip packages
        run: pip list || true
      - name: Linting
        run: make lint check-format                  
      - name: Run tests
        run: make test
      - name: publish to pip registry
        if: ${{ inputs.publish && inputs.publish != 'false' }}
        run: |
           echo "publish"
           pip install twine
#          echo -e "[pypi]" >> ~/.pypirc
#          echo -e "repository = $PYPI_REPOSITORY" >> ~/.pypirc
#          echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
#          echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
#          twine upload dist_python/*
        env: 
          PYPI_REPOSITORY: ${{env.PYPI_REGISTRY}}
          PYPI_USERNAME: ${{env.PYPI_USERNAME}}
          PYPI_PASSWORD: ${{secrets.PYPI_PASSWORD}}       
