name: deploy-product

on:
  workflow_call:
    secrets:
      DATAVISYN_BOT_REPO_TOKEN:
        required: true
      DV_CUSTOMERS:
        required: true
      DV_DEVOPS:
        required: true
      DV_QMS:
        required: true
      DV_AWS_ECR_REGISTRY:
        required: false
      DV_BOT_USER:
        required: true
    inputs:
      stage:
        description: "stage that should be deployed (develop|qa|production)"
        required: true
        type: string
      customer:
        description: "customer for that the app should be deployed"
        required: true
        type: string
      add_revision_as_tag:
        description: "customer for that the app should be deployed"
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

concurrency:
  group: '${{ github.workflow }}-${{ github.ref || github.head_ref }}'
  cancel-in-progress: true

env:
  GA_VERSION: "main"
  WORKFLOW_BRANCH: "new_deployment"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    # outputs:
    #   output1: ${{ steps.step1.outputs.test }}
    #   output2: ${{ steps.step2.outputs.test }}
    steps:
      # checkout repo to get package.json
      - uses: actions/checkout@v3
      # checkout this workflow repository to get actions
      - uses: actions/checkout@v3
        with:
          repository: datavisyn/github-workflows
          ref: ${{ env.WORKFLOW_BRANCH }}
          path: ./tmp/github-workflows
      - uses: ./tmp/github-workflows/.github/actions/check-actor
        with:
          dv_devops: ${{ secrets.DV_DEVOPS }}
          dv_qms: ${{ secrets.DV_QMS }}
          actor: ${{ github.actor }}
          qms_are_allowed: "true"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.DV_AWS_ECR_ROLE }}
          aws_role: ${{ secrets.DV_AWS_ECR_ROLE }}
          aws-region: ${{ secrets.DV_AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.5.3
      - uses: ./tmp/github-workflows/.github/actions/get-product-parameters
        id: get-parameters
        with:
          dv_customers: ${{ secrets.DV_CUSTOMERS }}
          branch_name: ${{ github.ref_name }}
          time_zone: ${{ env.TIME_ZONE }}
      - name: trigger deployment
        uses: datavisyn/github-action-trigger-workflow@v1
        with:
          owner: "datavisyn"
          repo:  "infrastructure-k8s"
          github_token: ${{ secrets.DATAVISYN_BOT_REPO_TOKEN }}
          workflow_file_name: "deploy-app.yml"
          ref: ${{ env.WORKFLOW_BRANCH }}
          github_user: ${{ secrets.DV_BOT_USER }}
          client_payload: '{ "app": "${{ steps.get-parameters.outputs.app }}", "customer": "${{ inputs.customer }}", "stage": "${{ inputs.stage }}", "sub_app": "${{ steps.get-parameters.outputs.sub_app }}", "branch": "${{ steps.get-parameters.outputs.image_tag2 }}" }'
      - name: get revision label
        if: ${{ inputs.add_revision_as_tag == 'true' }}
        run: |
          echo "fetch labels of image"
          MANIFEST=$(aws ecr batch-get-image --repository-name "sightline/web" --image-id imageTag="${{ steps.get-parameters.outputs.image_tag2 }}" --accepted-media-types "application/vnd.docker.distribution.manifest.v1+json" --output json |jq -r '.images[].imageManifest' |jq -r '.history[0].v1Compatibility' |jq -r '.config.Labels | to_entries | .[] | select(.key=="org.opencontainers.image.revision") | .value')
          echo "$MANIFEST"
          echo "revision_label=$MANIFEST" >> "$GITHUB_OUTPUT"
