name: retag-image
#description: add a tag to existing AWS ECR image
#author: datavisyn

on:
  workflow_call:
    inputs:
      aws_role:
        type: string
        description: "aws role to push to the ecr registry"
        required: true
      aws_region:
        type: string
        description: "aws region to use"
        required: true
      ecr_repositories:
        type: string
        description: "ecr repositories (name only) - seperated with ,"
        required: true
      current_image_tag:
        type: string
        description: "current tag of the image"
        required: true
      additional_image_tag:
        type: string
        description: "additional image tag"
        required: true

jobs:
  retag-images:
    runs-on: ubuntu-20.04
    steps:
      - name: print variables
        run: echo "ADDITIONAL_IMAGE_TAG=$ADDITIONAL_IMAGE_TAG"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ inputs.aws_role }}
          aws-region: ${{ inputs.aws_region }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.5.3
      - name: retag image
        run: |
          mapfile -t array < <(echo "${REPOSITORY_NAMES}" | tr ',' "\n")
          for REPOSITORY_NAME in "${array[@]}"; do
            IMAGE_META="$(aws ecr describe-images --repository-name "$REPOSITORY_NAME" --image-ids imageTag="$CURRENT_IMAGE_TAG" --output json | jq --arg var "${ADDITIONAL_IMAGE_TAG}" '.imageDetails[0].imageTags | index( $var )')"
            if [[ -z "${IMAGE_META}" || "${IMAGE_META}" == "null" ]]; then
              MANIFEST="$(aws ecr batch-get-image --repository-name $REPOSITORY_NAME --image-ids imageTag="$CURRENT_IMAGE_TAG" --output json | jq --raw-output --join-output '.images[0].imageManifest')"
              aws ecr put-image --repository-name "$REPOSITORY_NAME" --image-tag "$ADDITIONAL_IMAGE_TAG" --image-manifest "$MANIFEST"
            else
              echo "image already tagged!"
            fi
          done;
        env:
          REPOSITORY_NAMES: ${{ inputs.ecr_repositories }}
          CURRENT_IMAGE_TAG: ${{ inputs.current_image_tag }}
          ADDITIONAL_IMAGE_TAG: ${{ inputs.additional_image_tag }}
        shell: bash
